name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: swiftcodes_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - run: pip install -r requirements.txt
    - run: pip install pytest pytest-asyncio
    
    - name: Verify test files
      run: |
        ls -la tests/
        python -c "import os; print('\nTest files:', [f for f in os.listdir('tests') if f.startswith('test_') and f.endswith('.py')])"
    
    - name: Run pytest with verbose output
      run: |
        pytest tests/ -v
      env:
        DATABASE_URL: postgresql://user:password@localhost:5432/swiftcodes_test